username = input("Введите имя пользователя: ")
titles = []
temp_title = input("Введите заголовок №1 заметки: ")
titles.append(temp_title)
temp_title = input("Введите заголовок №2 заметки: ")
titles.append(temp_title)
temp_title = input("Введите заголовок №3 заметки: ")
titles.append(temp_title)
content = input("Введите описание заметки: ")
status = input("Введите статус заметки (например, 'Активна', 'Выполнена'): ")
created_date = input("Введите дату создания заметки в формате 'дд.мм.гггг': ")
issue_date = input("Введите дату истечения заметки в формате 'дд.мм.гггг': ")

print("\nВы ввели следующие данные:")
print("Имя пользователя:", username)
print("Заголовки заметки:", titles)
print("Описание заметки:", content)
print("Статус заметки:", status)
print("Дата создания заметки:", created_date)
print("Дата истечения заметки:", issue_date)